image: node:8

pages:
  stage: deploy
  script:
  - mkdir .public
  - npm i -g npm@latest
  - npm i -g yarn lerna
  - lerna bootstrap --use-workspaces
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master